export default {
    HOME: '/',
    SETTINGS: '/settings',
    CREDITS: '/credits',
    PCAPS: '/pcaps',
    LIVE_SOURCES: '/live_sources',
    WORKFLOWS: '/workflows',
    SIMULATOR_VRX: '/simulator/vrx',
    LIVE: '/live',
    NETWORK: '/network',
    LIVE_SENDERS_PAGE: '/live/senders',
    CONFIGURE: 'configure',
    STREAMS_PAGE: 'streams',
    STREAM_COMPARISONS: '/stream_comparisons',
    DOWNLOAD_MANAGER: '/download_manager',
};
