export default {
    DEFAULT: '/',
    HOME: '/home',
    SETTINGS: '/settings',
    CREDITS: '/credits',
    PCAPS: '/pcaps',
    CAPTURE: '/capture',
    WORKFLOWS: '/workflows',
    SIMULATOR_VRX: '/simulator/vrx',
    LIVE: '/live',
    NETWORK: '/network',
    LIVE_SENDERS_PAGE: '/live/senders',
    CONFIGURE: 'configure',
    DROPPED_PACKETS: 'dropped_packets',
    STREAMS_PAGE: 'streams',
    STREAM_COMPARISONS: '/stream_comparisons',
    DOWNLOAD_MANAGER: '/download_manager',
};
