export default {
    LIVE: {
        IP_PARSED_FROM_SDP: 'IP_PARSED_FROM_SDP',
        SDP_VALIDATION_RESULTS: 'SDP_VALIDATION_RESULTS',
        STREAM_UPDATE: 'STREAM_UPDATE',
        NMOS_UPDATE: 'NMOS_UPDATE',
    },
    MEDIA: {
        MP3_FILE_RENDERED: 'MP3_FILE_RENDERED',
        MP3_FILE_FAILED: 'MP3_FILE_FAILED',
    },
    PCAP: {
        FILE_RECEIVED: 'PCAP_FILE_RECEIVED',
        FILE_PROCESSED: 'PCAP_FILE_PROCESSED',
        ANALYZING: 'PCAP_FILE_ANALYZING',
        FILE_FAILED: 'PCAP_FILE_FAILED',
        DONE: 'PCAP_FILE_PROCESSING_DONE',
        DELETED: 'PCAP_FILE_DELETED',
    },
};
