export default {
    PCAP: {
        FILE_RECEIVED: 'PCAP_FILE_RECEIVED',
        FILE_PROCESSED: 'PCAP_FILE_PROCESSED',
        ANALYZING: 'PCAP_FILE_ANALYZING',
        FILE_FAILED: 'PCAP_FILE_FAILED',
        DONE: 'PCAP_FILE_PROCESSING_DONE'
    },
    LIVE: {
        IP_PARSED_FROM_SDP: 'IP_PARSED_FROM_SDP',
        STREAM_UPDATE: 'STREAM_UPDATE',
        NMOS_UPDATE: 'NMOS_UPDATE'
    }
};
