option(BUILD_DEMOS "Build LIST SDK Demos" OFF)
option(BUILD_TESTS "Build tests for LIST SDK" OFF)
option(BUILD_APPS "Build LIST apps" OFF)
option(BUILD_ALL "Build all targets" OFF)

if(BUILD_ALL)
    set(BUILD_DEMOS ON)
    set(BUILD_TESTS ON)
    set(BUILD_APPS ON)
endif()

message(STATUS "BUILD_DEMOS: " ${BUILD_DEMOS})
message(STATUS "BUILD_TESTS: " ${BUILD_TESTS})
message(STATUS "BUILD_APPS: " ${BUILD_APPS})

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
