version: '3'
services:
    influxdb:
        image: influxdb:1.4.2
        volumes:
            - influxdb:/var/lib/influxdb

    mongo:
        image: mongo:4.1.10
        volumes:
            - mongo:/data/db

    rabbitmq:
        image: pedroalvesferreira/rabbitmq-with-web-mqtt

    listserver:
        image: ebutech/pi-list:${EBU_LIST_VERSION}
        ports:
            - '80'
        environment:
            - EBU_LIST_WEB_APP_DOMAIN=${EBU_LIST_WEB_APP_DOMAIN:-}
            - EBU_LIST_LIVE_MODE=${EBU_LIST_LIVE_MODE:-false}
        links:
            - influxdb
            - mongo
            - rabbitmq
        volumes:
            - ${EBU_LIST_HOST_DATA_FOLDER:-listserver}:/home/

volumes:
    mongo:
    listserver:
    influxdb:

networks:
    default:
        external: true
        name: build_agent_net
