version: "3"
services:
  influxdb:
    image: influxdb:1.4.2
    volumes:
      - influxdb:/var/lib/influxdb

  mongo:
    image: mongo:4.1.10
    volumes:
      - mongo:/data/db

  rabbitmq:
    image: pedroalvesferreira/rabbitmq-with-web-mqtt
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15675:15675"

  list_server:
    image: ebutech/pi-list # using the latest version
    ports:
      - "8080:8080"
      - "3030:3030"
    environment:
        - EBU_LIST_WEB_APP_DOMAIN=${EBU_LIST_WEB_APP_DOMAIN}
        - EBU_LIST_LIVE_MODE=${EBU_LIST_LIVE_MODE}
    links:
      - influxdb
      - mongo
      - rabbitmq
    volumes:
      - listserver:/home/

volumes:
  mongo:
  listserver:
  influxdb:
